### PR TITLE
Removed YOLO

### PR DESCRIPTION
**Pull request by fabean**
It seemed wrong to put that there right after explaining that you could run this at much as possible.

### CODE REVIEW

**Comment by zhawkins** [comment]
Were you thinking something else might be more appropriate? 🤔

**Comment by zhawkins** [comment]
@fabean hey, man did you mean to fork this repo and pull request your updates against your own repo? Your updates look cool but I don't think we'll be changing the project name to "Code Koalas D8 theme Generator"

**Comment by fabean** [comment]
@zhawkins  I meant to merge those back into my own version. The name change started when I wanted to run both generators side by side. If you're up for some extra features my plan was to add: 

- Auto add libraries to theme.libraries.yml
- Allow for more options of css grids (specifically bulma)
- Add a PostCSS processor for gulp to allow components to use that instead of scss.

Just today I hacked together the libraries part, it currently works if your theme's directory name matches your theme name, which to me should always be the case but when adding a component you've lost the context of the original theme you generated. I made it so the library automatically adds both css & js which isn't how you're handling the creation of components at the moment, so that should be broken out to when you add the js itself but then I need to parse the yml file itself instead of just throwing it on the end.

**Comment by fabean** [comment]
Reverted the name change things I did and created the pull for the new features: https://github.com/mediacurrent/theme_generator_8/pull/23

**Comment by zhawkins** [comment]
We've updated the repo quite a bit to bring Yeoman and friends up to date. I'm going to close this PR now. Please feel free to open another one.

**Pull request closed without merging**
